

last_vl_date = "SELECT DATE_FORMAT(DateOfCurrentVL, '%d-%m-%Y') DateOfCurrentVL FROM (SELECT @row_no := IF(@prev_val = e.patient_id , @row_no + 1, 1) AS Occurrence, @prev_val := e.patient_id AS person_id, p.`identifier` Pepid, e.`encounter_datetime` DateOfCurrentVL, o.`value_numeric` CurrentVL, Date_Result_Received FROM `obs` o LEFT JOIN `encounter` e ON o.`encounter_id`=e.`encounter_id` LEFT JOIN `patient_identifier` p ON o.`person_id` = p.`patient_id` AND p.`identifier_type` = 4 AND p.`preferred` = 1 LEFT JOIN (SELECT DISTINCT person_id, encounter_id, value_datetime AS Date_Result_Received FROM obs  WHERE concept_id = 165987 AND voided=0) AS d ON  o.person_id=d.person_id AND o.`encounter_id`=d.`encounter_id`, (SELECT @row_no := 0) X, (SELECT @prev_val := '') Y WHERE o.`concept_id` = 856 AND e.`encounter_type` = 11 AND e.`form_id` = 21  AND o.`voided` = 0 AND  e.`encounter_datetime` <= CURDATE() AND e.patient_id=@patient_id ORDER BY e.patient_id, e.`encounter_datetime` DESC) a WHERE Occurrence = 1 AND DateOfCurrentVL <= CURDATE()"
last_vl_result = "SELECT CurrentVL FROM (SELECT @row_no := IF(@prev_val = e.patient_id , @row_no + 1, 1) AS Occurrence, @prev_val := e.patient_id AS person_id, p.`identifier` Pepid, DATE_FORMAT(e.`encounter_datetime`, '%d-%m-%Y') DateOfCurrentVL, o.`value_numeric` CurrentVL, Date_Result_Received FROM `obs` o LEFT JOIN `encounter` e ON o.`encounter_id`=e.`encounter_id` LEFT JOIN `patient_identifier` p ON o.`person_id` = p.`patient_id` AND p.`identifier_type` = 4 AND p.`preferred` = 1 LEFT JOIN (SELECT DISTINCT person_id, encounter_id, value_datetime AS Date_Result_Received FROM obs  WHERE concept_id = 165987 AND voided=0) AS d ON  o.person_id=d.person_id AND o.`encounter_id`=d.`encounter_id`, (SELECT @row_no := 0) X, (SELECT @prev_val := '') Y WHERE o.`concept_id` = 856 AND e.`encounter_type` = 11 AND e.`form_id` = 21  AND o.`voided` = 0 AND  e.`encounter_datetime` <= CURDATE() AND e.patient_id=@patient_id ORDER BY e.patient_id, e.`encounter_datetime` DESC) a WHERE Occurrence = 1 AND DateOfCurrentVL <= CURDATE()"

last_sample_date = "SELECT DATE_FORMAT(Last_VL_Sample_Date, '%d-%m-%Y') FROM (SELECT @row_no := IF(@prev_val = o.person_id , @row_no + 1, 1) AS Occurrence, @prev_val := o.person_id AS person_id, person_id test, o.encounter_id, `obs_datetime`, value_datetime AS Last_VL_Sample_Date FROM obs o LEFT JOIN `encounter` e ON o.`encounter_id`=e.`encounter_id`, (SELECT @row_no := 0) X, (SELECT @prev_val := '') Y WHERE concept_id = 159951 AND o.voided=0 AND e.`encounter_type` = 11 AND e.`form_id` = 21 AND o.`obs_datetime` <= CURDATE()  AND o.person_id=@patient_id ORDER BY o.person_id, o.`obs_datetime` DESC)a WHERE Occurrence = 1"

client_name = "SELECT CONCAT_WS(', ', family_name, given_name, CONCAT('(',gender,')'), CurrentAge) FROM (SELECT p.`given_name`, p.`family_name`, pp.`gender`, TIMESTAMPDIFF(YEAR, pp.`birthdate`, CURDATE()) AS CurrentAge FROM `person_name` p LEFT JOIN `person` pp ON p.`person_id`=pp.`person_id` LEFT JOIN `patient_identifier` ppp ON p.`person_id`=ppp.`patient_id` WHERE ppp.`voided`=0 AND ppp.`patient_id`=@patient_id GROUP BY p.`person_id`)a"

client_age = "SELECT TIMESTAMPDIFF(YEAR, p.`birthdate`, CURDATE()) AS CurrentAge FROM`person` p WHERE p.`voided` = 0 AND p.`person_id` =@patient_id GROUP BY p.`person_id`"

last_refill_date = "SELECT DATE_FORMAT(LastPickupDate, '%d-%m-%Y') LastPickupDate FROM (SELECT a.patient_id, a. LastPickupDate, a.`encounter_id`, b.DaysOfARVRefill FROM (SELECT @row_no := IF(@prev_val = e.patient_id , @row_no + 1, 1) AS Occ, @prev_val := e.patient_id AS patient_id, e.`encounter_datetime` LastPickupDate, e.`encounter_id` FROM `encounter` e, (SELECT @row_no := 0) X, (SELECT @prev_val := '') Y WHERE e.`encounter_type` = 13 AND e.`form_id` = 27 AND e.`voided` = 0 AND e.`encounter_datetime` <= CURDATE() AND `patient_id`=@patient_id ORDER BY e.patient_id, e.`encounter_datetime` DESC) a LEFT JOIN (SELECT o.`person_id`, o.encounter_id, o.`obs_id`, o.`value_numeric` DaysOfARVRefill FROM `obs` o WHERE o.concept_id = 159368 AND o.`voided` = 0  AND o.`person_id`=@patient_id AND obs_group_id IN (SELECT obs_id FROM obs WHERE concept_id = 162240 AND `voided` = 0) GROUP BY o.encounter_id) b ON a.encounter_id = b.encounter_id WHERE a.Occ=1)a"

last_refill_days = "SELECT DaysOfARVRefill FROM (SELECT a.patient_id, a. LastPickupDate, a.`encounter_id`, b.DaysOfARVRefill FROM (SELECT @row_no := IF(@prev_val = e.patient_id , @row_no + 1, 1) AS Occ, @prev_val := e.patient_id AS patient_id, e.`encounter_datetime` LastPickupDate, e.`encounter_id` FROM `encounter` e, (SELECT @row_no := 0) X, (SELECT @prev_val := '') Y WHERE e.`encounter_type` = 13 AND e.`form_id` = 27 AND e.`voided` = 0 AND e.`encounter_datetime` <= CURDATE() AND `patient_id`=@patient_id ORDER BY e.patient_id, e.`encounter_datetime` DESC) a LEFT JOIN (SELECT o.`person_id`, o.encounter_id, o.`obs_id`, o.`value_numeric` DaysOfARVRefill FROM `obs` o WHERE o.concept_id = 159368 AND o.`voided` = 0 AND o.`person_id`=@patient_id AND obs_group_id IN (SELECT obs_id FROM obs WHERE concept_id = 162240 AND `voided` = 0) GROUP BY o.encounter_id) b ON a.encounter_id = b.encounter_id WHERE a.Occ=1)a"



last_vl_date_raw = "SELECT DATE(DateOfCurrentVL) DateOfCurrentVL FROM (SELECT @row_no := IF(@prev_val = e.patient_id , @row_no + 1, 1) AS Occurrence, @prev_val := e.patient_id AS person_id, p.`identifier` Pepid, e.`encounter_datetime` DateOfCurrentVL, o.`value_numeric` CurrentVL, Date_Result_Received FROM `obs` o LEFT JOIN `encounter` e ON o.`encounter_id`=e.`encounter_id` LEFT JOIN `patient_identifier` p ON o.`person_id` = p.`patient_id` AND p.`identifier_type` = 4 AND p.`preferred` = 1 LEFT JOIN (SELECT DISTINCT person_id, encounter_id, value_datetime AS Date_Result_Received FROM obs  WHERE concept_id = 165987 AND voided=0) AS d ON  o.person_id=d.person_id AND o.`encounter_id`=d.`encounter_id`, (SELECT @row_no := 0) X, (SELECT @prev_val := '') Y WHERE o.`concept_id` = 856 AND e.`encounter_type` = 11 AND e.`form_id` = 21  AND o.`voided` = 0 AND  e.`encounter_datetime` <= CURDATE() AND e.patient_id=@patient_id ORDER BY e.patient_id, e.`encounter_datetime` DESC) a WHERE Occurrence = 1 AND DateOfCurrentVL <= CURDATE()"
last_sample_date_raw = "SELECT Last_VL_Sample_Date FROM (SELECT @row_no := IF(@prev_val = o.person_id , @row_no + 1, 1) AS Occurrence, @prev_val := o.person_id AS person_id, person_id test, o.encounter_id, `obs_datetime`, value_datetime AS Last_VL_Sample_Date FROM obs o LEFT JOIN `encounter` e ON o.`encounter_id`=e.`encounter_id`, (SELECT @row_no := 0) X, (SELECT @prev_val := '') Y WHERE concept_id = 159951 AND o.voided=0 AND e.`encounter_type` = 11 AND e.`form_id` = 21 AND o.`obs_datetime` <= CURDATE()  AND o.person_id=@patient_id ORDER BY o.person_id, o.`obs_datetime` DESC)a WHERE Occurrence = 1"
last_refill_date_raw = "SELECT DATE(LastPickupDate) LastPickupDate FROM (SELECT a.patient_id, a. LastPickupDate, a.`encounter_id`, b.DaysOfARVRefill FROM (SELECT @row_no := IF(@prev_val = e.patient_id , @row_no + 1, 1) AS Occ, @prev_val := e.patient_id AS patient_id, e.`encounter_datetime` LastPickupDate, e.`encounter_id` FROM `encounter` e, (SELECT @row_no := 0) X, (SELECT @prev_val := '') Y WHERE e.`encounter_type` = 13 AND e.`form_id` = 27 AND e.`voided` = 0 AND e.`encounter_datetime` <= CURDATE() AND `patient_id`=@patient_id ORDER BY e.patient_id, e.`encounter_datetime` DESC) a LEFT JOIN (SELECT o.`person_id`, o.encounter_id, o.`obs_id`, o.`value_numeric` DaysOfARVRefill FROM `obs` o WHERE o.concept_id = 159368 AND o.`voided` = 0  AND o.`person_id`=@patient_id AND obs_group_id IN (SELECT obs_id FROM obs WHERE concept_id = 162240 AND `voided` = 0) GROUP BY o.encounter_id) b ON a.encounter_id = b.encounter_id WHERE a.Occ=1)a"